fmod EXP is

  pr VAR .
  pr INT .

  sorts Exp Assign Op Code LambdaA NormalForm .
  subsort Var Int LambdaA < Exp .
  subsort Exp Assign < Code .
  subsort LambdaA Int < NormalForm .

  op nullAssign : -> Assign [ctor] .
  op _:=_ : Var Exp -> Assign [ctor] .
  op _,_ : Assign Assign -> Assign [assoc comm ctor id: nullAssign] . 

  op lambda_._ : Var Exp -> LambdaA [ctor] .
  op __ : Exp Exp -> Exp [ctor] .
  op let_in_ : Assign Exp -> Exp [ctor] .
  op ___ : Exp Op Exp -> Exp [ctor] .

  op +. : -> Op [ctor] .

  vars I : Int .
  vars E E' : Exp .
  vars V V' V'' : Var .
  vars O : Op .
  vars N N' : Nat .
  vars A A' : Assign .

  *** Substitution

  op _[_/_] : Code Var Var -> Code .

  eq [int] : I [V' / V] = I .
  eq [var1] : V [V' / V] = V' .
  eq [var2] : V'' [V' / V] = V'' [owise] .

  eq [nullAssign] : nullAssign [V' / V] = nullAssign .

  eq [assign1] : 
    (V := E) [V' / V''] = (V [V' / V'']) := (E [V' / V'']) .

  eq [assign2] : 
    (A , A') [V / V'] = (A [V / V']) , (A' [V / V']) .

  ceq [let-capture] : 
    (let ((V' := E) , A) in E') [V' / V] = 
      (let (((V' := E) , A) [V'' / V']) in (E' [V'' / V'])) [V' / V]
      if V'' := fresh(V', (let ((V' := E) , A) in E') V) .

  eq [let-shadow] : 
    (let ((V := E) , A) in E') [V' / V] = let ((V := E) , A) in E' [owise] .

  eq [let-dist] : 
    (let A in E) [V' / V] = let (A [V' / V]) in (E [V' / V]) [owise] .

  eq [app] : (E V) [V' / V''] = (E [V' / V'']) (V [V' / V'']) . 

  eq [comp] : (E O E') [V' / V] = (E [V' / V]) O (E' [V' / V]) .  

  ceq [lambda1] : 
  (lambda V'' . E) [V' / V] = lambda V'' . (E [V' / V])
    if V'' =/= V' /\ V'' =/= V . 

  ceq [lambda2] : 
    (lambda V . E) [V / V'] = (lambda V'' . (E [V'' / V])) [V / V']
      if V'' := fresh(V, E V') .

  eq [lambda3] : 
    (lambda V . E) [V' / V] = lambda V . E .


  op next : Code -> Nat .

  eq [next-int] : next(I) = 0 .

  eq [next-var] : next(v(N)) = s(N) .

  eq [next-lambda] : next(lambda V . E) = max(next(V), next(E)) .

  eq [next-app] : next(E V) = max(next(E), next(V)) .

  eq [next-comp] : next(E O E') = max(next(E), next(E')) .
  
  eq [next-let] : next(let A in E) = max(next(A), next(E)) .

  eq [next-nullAssign] : next(nullAssign) = 0 .

  eq [next-assign1] : next(v(N) := E) = max(next(v(N)), next(E)) .

  eq [next-assign2] : next((v(N) := E) , A) = max(next(v(N) := E), next(A)) [owise] . 

  op fresh : Var Code -> Var .

  eq [fresh] : fresh(V, E) = v(max(next(V), next(E))) .
  
endfm
