mod SEMANTIC is

  pr HEAP .
  pr EXP .
  pr NORM .
  
  sorts Conf .

  op <_,_> : Heap Exp -> Conf [ctor] .
  op exec : Exp -> Conf .


  vars H H' H'' : Heap .
  vars V V' : Var .
  vars E E' : Exp .
  vars I I' : Int .
  vars A : Assign .
  vars F : NormalForm . 
  vars N : Nat .
  
  ceq [exec] : 
    exec(E) = < emptyHeap, E' >
      if < E' , N > := norm(E, 0) .

  crl [var] : 
    < H [V := E] , V > => < H' [V := F] , F >
    if < H , E > => < H' , F > .

  crl [app] :
    < H , E V > => < H'' , F >
    if < H , E > => < H' , lambda V' . E' > /\
      < H' , E' [V / V'] > => < H'' , F > .

  crl [let] : 
    < H , let A in E > => < H' , F > 
    if < bind(H, A) , E > => < H' , F > .

  crl [sum] : 
    < H , E +. E' > => < H'' , I + I' >
    if < H , E > => < H' , I > /\ < H' , E' > => < H'' , I' > .


  op op1 : -> Conf .
  eq op1 = < emptyHeap , let ((v(0) := (3 +. 2)) , (v(1) := (v(0) +. 1))) in (v(1) +. v(1)) > .

  op op2 : -> Conf .
  eq op2 = < [v(0) := 2] [v(1) := 3] ,

    let (

    (v(2) := (3 +. 2)) , 

    (v(4) := (let (v(5) := (v(2) +. 1)) in (lambda v(6) . (v(5) +. v(6)))))

    ) in 

    ((v(4) v(0)) +. (v(4) v(1))) > .

  op op3 : -> Conf .
  eq op3 = 
    < [v(0) := 1] [v(1) := 2] , let v(2) := (

      lambda v(0) . (let v(3) := v(0) in v(3))

    ) in ((v(2) v(1)) +. (v(2) v(0))) > . 

endm
